version: '3'
services:
  web:
    build: ./web  #dockerfileのパス
    volumes:
      - ./web/conf:/etc/nginx/conf.d  #マウント、ホスト:コンテナ
      - ./web/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    ports:
      - "8000:8000" #ポート指定、ホスト:コンテナ
    depends_on:
      - app  #appに依存

  db:
    build: ./db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  #実行時のコマンド
    ports:
      - "3306:3306" #ポート指定、ホスト:コンテナ
    environment:  #コンテナ内の環境変数を指定
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/mysql:/var/lib/mysql #マウント、ホスト:コンテナ
  
  app:
    build: ./app
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log  #uwsgi起動、socketで通信
    volumes: 
      - ./src:/code #マウント、ホスト:コンテナ
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - db  #dbに依存