# Generated by Django 4.1 on 2023-06-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='userid',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
