# Generated by Django 4.1 on 2023-06-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_User_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='introduction',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
