# Generated by Django 4.1 on 2023-06-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_User_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
